import unittest

from ntrust import anonpred

class TestFindAnonPredicate(unittest.TestCase):
    def test_1(self):
        self.assertEqual(anonpred.find_anonymous_predicates("구라라고 알려졌다. 바보라고 전해졌다. 아니라고 밝혀졌다. 신차임이 강조됐다. 문제점이 지적됐다."), ["알려졌다","전해졌다","밝혀졌다","강조됐다","지적됐다"])
        self.assertEqual(anonpred.find_anonymous_predicates("강력하게 주장했다."), ["주장했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("바보가 아니라는 주장을 내놨다."), ["주장을내놨다"])
        self.assertEqual(anonpred.find_anonymous_predicates("밥먹자고 강조했다."), ["강조했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("독립을 선언했다."), ["선언했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("선처를 당부했다."), ["당부했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("결백을 호소했다."), ["호소했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("그런 바람을 나타냈다."), ["바람을나타냈다"])
        self.assertEqual(anonpred.find_anonymous_predicates("아니라고 하소연 했다."), ["하소연했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("무척 아쉬워했다."), ["아쉬워했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("무척 안타까워했다."), ["안타까워했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("조심스럽게 우려했다."), ["우려했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("중복 우려를 표명했다."), ["우려를표명했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("아니라고 단언했다."), ["단언했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("그럴 것이라고 단정했다."), ["단정했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("주장을 일축했다."), ["일축했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("분명히 고수했다."), ["고수했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("분명히 했다."), ["분명히했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("촉구했다."), ["촉구했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("경고했다."), ["경고했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("으름장을 놨다."), ["으름장을놨다"])
        self.assertEqual(anonpred.find_anonymous_predicates("압박을 가했다."), ["압박을가했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("잘못된 점을 지적했다."), ["지적했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("볼을 꼬집었다."), ["꼬집었다"])
        self.assertEqual(anonpred.find_anonymous_predicates("야당을 비판했다."), ["비판했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("박근혜를 비난했다."), ["비난했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("이명박이 해명했다."), ["해명했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("안철수가 반발했다."), ["반발했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("아니라고 항변했다."), ["항변했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("노골적인 불쾌감을 표시했다."), ["불쾌감을표시했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("아니라고 목소리를 높였다."), ["목소리를높였다"])
        self.assertEqual(anonpred.find_anonymous_predicates("범인이라는 의혹을 제기했다."), ["의혹을제기했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라는 의문을 제기했다."), ["의문을제기했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라며 의아해 했다."), ["의아해했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라는 문제를 제기했다."), ["문제를제기했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주임을 시사했다."), ["시사했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라고 내다봤다."), ["내다봤다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라는 확신을 내비쳤다."), ["내비쳤다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라고 기대했다."), ["기대했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라고 전망했다."), ["전망했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라는 기대를 나타냈다."), ["기대를나타냈다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라는 관측도 나오고 있다."), ["관측도나오고있다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라고 평했다."), ["평했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라고 평가했다."), ["평가했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라고 분석했다."), ["분석했다"])
        #self.assertEqual(anonpred.find_anonymous_predicates("실소유주라고도 했다."), ["라고도했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라고 말할 정도다."), ["말할정도다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라고 털어놓았다."), ["털어놓았다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주가 아니라고 토로했다."), ["토로했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라고 귀띔했다."), ["귀띔했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라고 말하자 벌어진 입을 다물지 못했다."), ["벌어진입을다물지못했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라며 말을 제대로 잇지 못했다."), ["말을제대로잇지못했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라고 입을 모았다."), ["입을모았다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라며 자조적인 태도를 보였다."), ["자조적인태도를보였다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라며 흥분을 감추지 못했다."), ["흥분을감추지못했다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라고 말하기를 망설였다."), ["망설였다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라며 한마디 더 붙였다."), ["한마디더붙였다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라며 한숨을 쉬었다."), ["한숨을쉬었다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라며 혀를 내둘렀다."), ["혀를내둘렀다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라먀 완화된 어조로 나왔다."), ["완화된어조로나왔다"])
        self.assertEqual(anonpred.find_anonymous_predicates("실소유주라는 신중한 반응을 보였다."), ["신중한반응을보였다"])

        self.assertEqual(anonpred.find_anonymous_predicates("구라라고 알려졌을까 싶지만 그렇다고 알려졌습니다."), ["알려졌습니다"])
